import { Card } from '../ui/Card'
import { EmptyState } from '../ui/EmptyState'
import { Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getFinancialPeriodSummary } from '../../services/financeUtils'

// Renderiza a série financeira recebida pelo Dashboard sem manter uma lógica paralela.
export function PerformanceChart({ clientContracts, services, recurringContracts = [], view, periodValue, onViewChange }) {
  const summary = getFinancialPeriodSummary({ clientContracts, services, recurringContracts, view, periodValue })
  const hasRecords = clientContracts.length > 0 || services.length > 0 || recurringContracts.length > 0
  return <Card className="p-5"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold text-[#17213d]">Gráfico de desempenho</h2><p className="mt-1 text-xs text-[#8a91a8]">Recebimentos e valores pendentes</p></div><div className="flex items-center gap-4"><div className="flex gap-3 text-[10px] text-(--color-text-muted)"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-(--color-primary)" />Pago</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#f59e0b]" />A receber</span></div><div className="flex rounded-lg bg-(--color-primary-light) p-1"><button onClick={() => onViewChange('monthly')} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${view === 'monthly' ? 'bg-white text-(--color-primary) shadow-sm' : 'text-[#6B7280]'}`}>Mensal</button><button onClick={() => onViewChange('annual')} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${view === 'annual' ? 'bg-white text-(--color-primary) shadow-sm' : 'text-[#6B7280]'}`}>Anual</button></div></div></div><div className="h-64 w-full">{hasRecords ? <ResponsiveContainer width="100%" height="100%"><LineChart data={summary.data} margin={{ top: 8, right: 10, left: 0, bottom: 0 }}><XAxis dataKey="label" interval={view === 'monthly' ? 2 : 0} tick={{ fontSize: 10, fill: '#8a91a8' }} tickLine={false} axisLine={false} /><YAxis tick={{ fontSize: 10, fill: '#8a91a8' }} tickLine={false} axisLine={false} tickFormatter={(value) => `${value / 1000}k`} /><Tooltip formatter={(value, name) => [`R$ ${Number(value).toLocaleString('pt-BR')}`, name === 'paid' ? 'Pago' : 'A receber']} /><Legend content={() => null} /><Line type="monotone" dataKey="paid" name="paid" stroke="var(--color-primary)" strokeWidth={2.5} dot={false} /><Line type="monotone" dataKey="receivable" name="receivable" stroke="#f59e0b" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer> : <EmptyState title="Sem dados financeiros" description="Cadastre contratos ou serviços para visualizar o desempenho." />}</div></Card>
}
